#!/usr/bin/env python
import sys
import requests
import argparse
import json

def main(argv):
    p = argparse.ArgumentParser(description='DC/OS Fault Domain Detection')
    args = p.parse_args(argv)

    instance_info = requests.get('http://169.254.169.254/latest/dynamic/instance-identity/document').json()
    fault_domain = {"fault_domain":{"region":{"name": "aws/{}".format(instance_info['region'])},"zone":{"name": "aws/{}".format(instance_info['availabilityZone'])}}}
    print(json.dumps(fault_domain))

if __name__ == "__main__":
    main(sys.argv[1:])
